# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 15f6be82723325fe58b82105c501e73a3189e8509ee7866377cc95ce9aad2bac0c7f53917e82166603d6a60675de18972de32ca224fdc337a7dc8f75ea1f6fc5

test:
  secret_key_base: 1b2054cf97948bba08e2579446a9ccb1b0f31d69a88c9ca5aaa949b53535e6d0584e8486e375c21e04969234ca29552de2a0b783225ef603e5c922a20adbcc0f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
